# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UploadWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(546, 260)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(142, 22, 262, 192))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setMinimumSize(QtCore.QSize(80, 0))
        self.label_5.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(80, 0))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.text1 = QtWidgets.QLineEdit(self.widget)
        self.text1.setObjectName("text1")
        self.gridLayout.addWidget(self.text1, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.text2 = QtWidgets.QLineEdit(self.widget)
        self.text2.setObjectName("text2")
        self.gridLayout.addWidget(self.text2, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(80, 0))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.text3 = QtWidgets.QLineEdit(self.widget)
        self.text3.setObjectName("text3")
        self.gridLayout.addWidget(self.text3, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setMinimumSize(QtCore.QSize(80, 0))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.text4 = QtWidgets.QLineEdit(self.widget)
        self.text4.setObjectName("text4")
        self.gridLayout.addWidget(self.text4, 4, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.Confirm = QtWidgets.QPushButton(self.widget)
        self.Confirm.setStyleSheet("font: 12pt \"Adobe Heiti Std\";")
        self.Confirm.setObjectName("Confirm")
        self.gridLayout_2.addWidget(self.Confirm, 1, 0, 1, 1)
        self.Cancel = QtWidgets.QPushButton(self.widget)
        self.Cancel.setStyleSheet("font: 12pt \"Adobe Heiti Std\";")
        self.Cancel.setObjectName("Cancel")
        self.gridLayout_2.addWidget(self.Cancel, 1, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "种类："))
        self.label.setText(_translate("Form", "物品："))
        self.label_2.setText(_translate("Form", "数量："))
        self.label_3.setText(_translate("Form", "Wants："))
        self.label_4.setText(_translate("Form", "联系方式："))
        self.Confirm.setText(_translate("Form", "确定"))
        self.Cancel.setText(_translate("Form", "取消"))
