# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeleteWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AreYouSure(object):
    def setupUi(self, AreYouSure):
        AreYouSure.setObjectName("AreYouSure")
        AreYouSure.resize(415, 261)
        AreYouSure.setAutoFillBackground(False)
        self.layoutWidget = QtWidgets.QWidget(AreYouSure)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 150, 195, 36))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Yes = QtWidgets.QPushButton(self.layoutWidget)
        self.Yes.setStyleSheet("font: 12pt \"Adobe Heiti Std\";")
        self.Yes.setObjectName("Yes")
        self.gridLayout.addWidget(self.Yes, 0, 0, 1, 1)
        self.No = QtWidgets.QPushButton(self.layoutWidget)
        self.No.setStyleSheet("font: 12pt \"Adobe Heiti Std\";")
        self.No.setObjectName("No")
        self.gridLayout.addWidget(self.No, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(AreYouSure)
        self.label.setGeometry(QtCore.QRect(40, 80, 330, 30))
        self.label.setStyleSheet("font: 18pt \"黑体\";")
        self.label.setObjectName("label")

        self.retranslateUi(AreYouSure)
        QtCore.QMetaObject.connectSlotsByName(AreYouSure)

    def retranslateUi(self, AreYouSure):
        _translate = QtCore.QCoreApplication.translate
        AreYouSure.setWindowTitle(_translate("AreYouSure", "Form"))
        self.Yes.setText(_translate("AreYouSure", "确定"))
        self.No.setText(_translate("AreYouSure", "取消"))
        self.label.setText(_translate("AreYouSure", "你确定要删除该条记录吗"))
