# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegisSuccess.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisSuccess(object):
    def setupUi(self, RegisSuccess):
        RegisSuccess.setObjectName("RegisSuccess")
        RegisSuccess.resize(314, 154)
        self.widget = QtWidgets.QWidget(RegisSuccess)
        self.widget.setGeometry(QtCore.QRect(40, 30, 242, 91))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("font: 18pt \"黑体\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("font: 18pt \"黑体\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(RegisSuccess)
        QtCore.QMetaObject.connectSlotsByName(RegisSuccess)

    def retranslateUi(self, RegisSuccess):
        _translate = QtCore.QCoreApplication.translate
        RegisSuccess.setWindowTitle(_translate("RegisSuccess", "Form"))
        self.label.setText(_translate("RegisSuccess", "注册成功"))
        self.label_3.setText(_translate("RegisSuccess", "     "))
        self.label_2.setText(_translate("RegisSuccess", "请等待管理员审核"))
