# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UploadWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(381, 303)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(60, 30, 262, 231))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setMinimumSize(QtCore.QSize(80, 0))
        self.label_5.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(80, 0))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(self.widget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 1, 1, 1, 1)
        self.label2 = QtWidgets.QLabel(self.widget)
        self.label2.setMinimumSize(QtCore.QSize(80, 0))
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 2, 0, 1, 1)
        self.want = QtWidgets.QLineEdit(self.widget)
        self.want.setObjectName("want")
        self.gridLayout.addWidget(self.want, 2, 1, 1, 1)
        self.label3 = QtWidgets.QLabel(self.widget)
        self.label3.setMinimumSize(QtCore.QSize(80, 0))
        self.label3.setObjectName("label3")
        self.gridLayout.addWidget(self.label3, 3, 0, 1, 1)
        self.info = QtWidgets.QLineEdit(self.widget)
        self.info.setObjectName("info")
        self.gridLayout.addWidget(self.info, 3, 1, 1, 1)
        self.hint = QtWidgets.QLabel(self.widget)
        self.hint.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hint.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hint.setObjectName("hint")
        self.gridLayout.addWidget(self.hint, 4, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.Confirm = QtWidgets.QPushButton(self.widget)
        self.Confirm.setStyleSheet("font: 12pt \"Adobe Heiti Std\";")
        self.Confirm.setObjectName("Confirm")
        self.gridLayout_2.addWidget(self.Confirm, 1, 0, 1, 1)
        self.Cancel = QtWidgets.QPushButton(self.widget)
        self.Cancel.setStyleSheet("font: 12pt \"Adobe Heiti Std\";")
        self.Cancel.setObjectName("Cancel")
        self.gridLayout_2.addWidget(self.Cancel, 1, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "种类："))
        self.label.setText(_translate("Form", "物品："))
        self.label2.setText(_translate("Form", "Wants："))
        self.label3.setText(_translate("Form", "详细信息："))
        self.hint.setText(_translate("Form", "[提示信息]"))
        self.Confirm.setText(_translate("Form", "确定"))
        self.Cancel.setText(_translate("Form", "取消"))
